require 'cancan'
require 'active_model_serializers'
require 'active_model_serializers/cancan/version'
require 'active_model_serializers/cancan/helpers'
require 'active_model_serializers/cancan/associations'
require 'active_model_serializers/cancan/abilities'
